### ISSUE TITLE
Aprovação de artigos por user ADMIN

### ISSUE THREAD

**Issue by rodolfobandeira** [php-br-org/php-br#11]
1) Se o usuario for ADMIN, listar todos artigos aguardando aprovação. 
2) Criar action para aprovar o artigo. 
3) Também será necessário desaprovar um artigo aprovado.
4) Recusar aprovação com uma caixa de texto. Assim o admin recusa o pedido de aprovação e a mensagem de recusa aparece para o usuário.

**Comment by zrod** [comment]
Feito, exceto pelo 4o item. Falta adicionar uma msg explicativa ao usuario do porque seu artigo foi reprovado.

**Comment by rodolfobandeira** [comment]
:+1:

**Comment by rodolfobandeira** [comment]
Vou fechar esse issue e criar um somente para o Item 4
