### ISSUE TITLE
Discus bundle

### ISSUE THREAD

**Issue by rodolfobandeira** [php-br-org/php-br#13]
@zrod instalei o discuss bundle mas ele tem API_KEY e SECRET_KEY no parameters.yml.
Como o parameters.yml não esta no commit, como fazemos?

**Comment by zrod** [comment]
So remover do .gitignore
Falando em parameters.yml, use uma hash "secret" diferente em producao (se ja nao for o caso).

**Comment by zrod** [comment]
Tente adicionar o parameters.yml no git agora (faca um pull antes).

**Comment by rodolfobandeira** [comment]
blz! @zrod 
ja mudei no server pra usar config_prod.yml e parameters_prod.yml 

Tmb editei o .gitignore arrumando o web/js/*
