### ISSUE TITLE
ERRO - doctrine:generate:crud

### ISSUE THREAD

**Issue by rodolfobandeira** [php-br-org/php-br#2]
@zrod nao sei como vc criou o entity Artigos, mas estou tentando criar o "url encurtator" usando o 
```
doctrine:generate:entity 
```
e depois:
```
doctrine:generate:crud 
```
O que acontece é que estou recebendo erro qdo rodo o comando de crud. Outro detalhe eh que mesmo com meu Entity/Url.php parecendo estar nos padroes corretos, quando rodo um doctrine:schema:update ele nao "detecta" essa nova entity. Nao tentei usando yml, xml.. somente usando anotattions. Tem alguma pista? :worried:  Tentando criar o arquivo na entity na mao tmb nao vai.. tentei copiar o Artigos.php para outro nome com outros valores e nada. Tmb tentei executar os comandos de schema:update depois de limpar o cache e tmb nada.. Tmb tentei dar um schema:drop e depois schema:create e nada.. 

```
[Doctrine\ORM\Mapping\MappingException]
Class "Phpbr\Bundle\AppBundle\Entity\Url" is not a valid entity or mapped super class.
```

**Comment by zrod** [comment]
Voce esta usando Vagrant?

Eu criei a entidade pelo cli (doctrine:generate:entity), com o namespace "PhpbrAppBundle:Artigo", usando yml.

Tem como colar a entidade Url gerada?

Nao cheguei a usar o CRUD, fiz o resto a mao mesmo.

Sempre que faco alteracoes na entidade (yml), eu rodo um:
```
doctrine:generate:entities PhpbrAppBundle:Artigo --no-backup
```

Geralmente costumo gerar o repository ali na hora mas o mudo para /Repository/ ao inves de /Entity/

Tente criar novamente por yml, certifique-se de que o namespace esteja correto, pule o CRUD, e em seguida rode o doctrine:schema:update --force.

**Comment by rodolfobandeira** [comment]
com yml foi!!!! :tada: :+1: :+1: :+1: :+1: :+1:
