### ISSUE TITLE
dploy.io

### ISSUE THREAD

**Issue by rodolfobandeira** [php-br-org/php-br#28]
O deployment para production esta configurado mas ainda esta manual. Por enquanto é necessário ir no dploy.io e selecionar qual commit irá para production e enviar.

Estou pensando em configurar o dployment automatico cada vez q um commit vai para master o que acham?

@zrod @DeToNeS

**Comment by DeToNeS** [comment]
Eu não tenho propriedade para opinar, até ontem eu desconhecia o dploy.io :smile:

**Comment by zrod** [comment]
Voces que sabem. Eu pessoalmente prefiro nao ativar deploy a cada commit em master, as vezes acontece de subirmos algo errado / acidentalmente.

**Comment by rodolfobandeira** [comment]
:+1:
