### ISSUE TITLE
TextArea Countdown Bundle

### ISSUE THREAD

**Issue by rodolfobandeira** [php-br-org/php-br#3]
Achei esse bundle que promete um textarea com countdown. Seria legal usar no resume textarea o que acha?

https://github.com/Prometee/BSkyTextAreaCountdownBundle

**Comment by rodolfobandeira** [comment]
Tentei instalar mas deu erro. Nao sei como habilitar o textareacountdown no form type dos artigos.

@b6e7a66d23e8fca3a901193a04df00c40c20a4c7

**Comment by zrod** [comment]
Countdown voce diz algo como "X caracteres restantes" ?
Se sim, podemos fazer por JS.

**Comment by rodolfobandeira** [comment]
Aham, vai ter q rolar feito por nos mesmo.. vou copiar os js do bundle para nosso bundle

**Comment by rodolfobandeira** [comment]
Conforme sugestão do @zrod um bundle para isso é muita coisa. Podemos fazer um javascript customizado!

**Comment by zrod** [comment]
Na minha lista de afazeres!

**Comment by DeToNeS** [comment]
Montei algo, quem puder dar uma olhada. Se estiver tudo ok, faço o pull request, agora vou dormir! :smile:
