### ISSUE TITLE
Bug - Depois do login no site, redirecionar para a última página.

### ISSUE THREAD

**Issue by rodolfobandeira** [php-br-org/php-br#47]
Para simular:

1) SEM estar logado, clicar no link Forum;
2) Clicar em um tópico;
3) Clicar em Novo Tópico;
4) Será redirecionado para o formulário de login;
5) Depois de fazer o login, ele cai na pagina inicial. Arrumar para que ele retorne para o Inserir Novo Tópico;

**Comment by zrod** [comment]
Corrigido, removido as seguintes linhas:

```
if ('anon.' == $usuario) {
    return $this->redirect($this->generateUrl('fos_user_security_login'));
}
```

Usar, ao inves, o security.yml:
access_control:
- { path: ^/forum/novo, role: ROLE_USER }
