### ISSUE TITLE
Forcar usuarios a entrar apenas id do github

### ISSUE THREAD

**Issue by zrod** [php-br-org/php-br#53]
Ao cadastrar nova conta, usuarios tem a opcao de inserir suas contas github/twitter/linkedin.

Alguns acabam colocando o endereco http por inteiro, enquanto que o twig esta configurado para exibir o link ja' com http://

Exemplo:
http://www.php-br.org/usuario/bugao7

Solucao:
- Evitar que usuarios possam inserir endereco http em tais campos.
- Alterar twig para pre-popular com http correto.

Nao podemos deixar os campos livres para http, uma vez que qualquer coisa pode ser inserida no lugar do linkedin/github/etc.

**Comment by rodolfobandeira** [comment]
Para modificar o Registration, poderiamos fazer um override no RegistrationController. O problema q para sobrescrever, teriamos q usar o getParent() e cada bundle so pode extender 1 vez. 

Poderiamos usar eventlisteners. O problema eh q so temos evento Antes de montar o form, ou depois quando ele ja fez o successful registration. 
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/controller_events.md

Acredito que o melhor seria deixar o user registrar o que quiser, e tratar no twig q mostra o perfil do user. Pode ser?

**Comment by rodolfobandeira** [comment]
Fiz usando validation.yml
