### ISSUE TITLE
Exibir numero de comentarios na lista de artigos

### ISSUE THREAD

**Issue by zrod** [php-br-org/php-br#55]
Verificar se e' possivel extrair o numero de comentarios de um artigo do disqus, talvez guarda-lo na base, e exibir na lista de artigos, como na pagina principal.

**Comment by rodolfobandeira** [comment]
Feito, porem esta com um bug. So esta mostrando o label nos dois primeiros artigos. Acredito q seja javascript

**Comment by rodolfobandeira** [comment]
Feito! @zrod
